name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build dependency
      run: sudo apt-get install -y libdb-dev libglib2.0-dev
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-dbm=BerkeleyDB
    - name: make
      run: make V=1 VERBOSE=1
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
