name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: fedora:rawhide

    steps:
    - uses: actions/checkout@v2
    - name: install build dependency
      run: sudo dnf install -y gcc-c++ libdb-devel glib2-devel make gnome-common wget
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-dbm=BerkeleyDB
    - name: make
      run: make V=1 VERBOSE=1
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
